
name: Playwright Tests
on:
  push:
    branches:
      - main  

jobs:
  playwright-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1.5.5
