name: Playwright Tests
on: [push]
jobs: 
  playwright-run:
     runs-on: windows-latest
     steps:  
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: Run Playwright tests
         uses: microsoft/playwright-github-action@v1.5.5
          
         with:
           start: npm start
